 "use client";
import {useEffect,useState} from "react";import {Github,Plus,Hammer,Home,Clock3,Settings,CheckCircle2,Download,Smartphone,ChevronRight,ShieldCheck,LogIn,RefreshCw} from "lucide-react";
export default function Page(){
 const [tab,setTab]=useState("home"),[repos,setRepos]=useState<any[]>([]),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [name,setName]=useState("My New App"),[repo,setRepo]=useState(""),[ref,setRef]=useState("main");
 async function loadRepos(){setBusy(true);const r=await fetch("/api/github/repos");if(r.ok){setRepos(await r.json());setConnected(true)}else setMsg("Connect GitHub first.");setBusy(false)}
 async function createBuild(){setBusy(true);setMsg("");const r=await fetch("/api/build",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,source:repo,ref,output:"apk"})});const j=await r.json();setMsg(j.message||`Build ${j.id} submitted.`);setBusy(false)}
 useEffect(()=>{loadRepos()},[]);
 return <main className="shell"><aside><div className="brand"><i><Hammer size={18}/></i>ForgeAPK</div><nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home/>Home</button><button className={tab==="create"?"active":""} onClick={()=>setTab("create")}><Plus/>Create app</button><button className={tab==="builds"?"active":""} onClick={()=>setTab("builds")}><Clock3/>Builds</button></nav><div className="bottom"><button><Settings/>Settings</button><small>Production starter</small></div></aside>
 <section className="content"><header className="mobile"><div className="brand"><i><Hammer size={16}/></i>ForgeAPK</div></header>
 {tab==="home"&&<><div className="hero"><div><em>⚡ Cloud Android builds</em><h1>Build APKs without the headache.</h1><p>GitHub in, APK out. ForgeAPK handles repositories, build jobs, artifacts and a mobile-first dashboard.</p></div><button className="primary" onClick={()=>setTab("create")}><Plus/>Create app</button></div><div className="actions"><button onClick={()=>{setTab("create");loadRepos()}}><Github/><div><b>{connected?"GitHub connected":"Connect GitHub"}</b><span>{busy?"Loading repositories…":"Import and build your repositories."}</span></div><ChevronRight/></button><button onClick={()=>setTab("create")}><Plus/><div><b>New project</b><span>Configure an Android build.</span></div><ChevronRight/></button></div><h2>Overview</h2><div className="stats"><div><b>5</b><small>Free builds / month</small></div><div><b>{repos.length}</b><small>GitHub repositories</small></div><div><b>Ready</b><small>Build service</small></div></div></>}
 {tab==="create"&&<div className="page"><button className="back" onClick={()=>setTab("home")}>← Back</button><em>⚙ Build configuration</em><h1>Create an APK</h1><p>Pick a GitHub repository and submit a cloud build.</p><article><h3>GitHub repository</h3>{!connected&&<button className="primary" onClick={()=>location.href="/api/auth/github"}><LogIn/>Connect GitHub</button>}{connected&&<><label>Repository</label><select value={repo} onChange={e=>setRepo(e.target.value)}><option value="">Choose repository</option>{repos.map(r=><option key={r.id} value={r.clone_url}>{r.full_name}{r.private?" · private":""}</option>)}</select><label>Branch</label><input value={ref} onChange={e=>setRef(e.target.value)}/><label>App name</label><input value={name} onChange={e=>setName(e.target.value)}/><div className="two"><div><label>Output</label><select><option>APK</option><option>AAB</option></select></div><div><label>Build</label><select><option>Release</option><option>Debug</option></select></div></div><button className="primary buildBtn" disabled={!repo||busy} onClick={createBuild}><Hammer/>{busy?"Submitting…":"Build APK"}</button>{msg&&<p className="notice">{msg}</p>}</>}</article><article className="security"><ShieldCheck/><div><b>Isolated builds</b><small>Repositories are executed only by the separate worker, never by the Next.js web process.</small></div></article></div>}
 {tab==="builds"&&<div className="page"><em>🕘 Build history</em><h1>Builds</h1><p>Track submitted builds and artifacts.</p><article className="empty"><RefreshCw/><b>Build history is database-backed.</b><small>Run the Prisma migration and worker to see live records here.</small></article></div>}
 </section><nav className="mobileNav"><button onClick={()=>setTab("home")}><Home/>Home</button><button onClick={()=>setTab("create")}><Plus/>Create</button><button onClick={()=>setTab("builds")}><Clock3/>Builds</button></nav></main>
}